#!/usr/bin/env node

/**
 * Synchronizes version numbers from package.json (and git) to the iOS and
 * Android builds. Run before a mobile build so the store metadata matches the
 * app.
 *
 * Two numbers identify a build:
 * - Marketing version (package.json `version`): Android `versionName`,
 *   iOS `MARKETING_VERSION` (CFBundleShortVersionString). Written into the
 *   tracked native files; it changes only on a prod release, so a sync between
 *   releases leaves those files as committed.
 * - Build number (git commit count): Android `versionCode` (computed by
 *   app/android/app/build.gradle itself) and iOS `CURRENT_PROJECT_VERSION`
 *   (CFBundleVersion), written here into the gitignored
 *   app/ios/App/BuildNumber.xcconfig. The stores require it to strictly
 *   increase per upload. Same source as the in-app sidebar build number, so the
 *   value shown in the app matches the Play Console / App Store Connect upload.
 *   Neither lands in a tracked file, so a build never dirties the tree.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

/**
 * Monotonic build number from the git commit count. Stays in sync with the
 * in-app sidebar (app/src/lib/version.ts). Throws if git can't produce an
 * integer, so a release build fails loudly rather than shipping a bad
 * versionCode.
 */
function getBuildNumber() {
  const raw = execSync('git rev-list --count HEAD').toString().trim();
  const count = Number(raw);
  if (!Number.isInteger(count) || count <= 0) {
    throw new Error(`Could not derive build number from git: "${raw}"`);
  }
  return count;
}

/** Set Android versionName (marketing version). */
function applyGradleVersion(text, version) {
  return text.replace(/versionName ".*"/, `versionName "${version}"`);
}

/** Set iOS MARKETING_VERSION (marketing version) in every build config. */
function applyXcodeVersion(text, version) {
  return text.replace(/MARKETING_VERSION = [\d.]+;/g, `MARKETING_VERSION = ${version};`);
}

/** Contents of app/ios/App/BuildNumber.xcconfig, read by Version.xcconfig. */
function buildNumberXcconfig(build) {
  return `// Generated by scripts/sync-version.js; gitignored.\nCURRENT_PROJECT_VERSION = ${build}\n`;
}

function main() {
  const packageJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, '../app/package.json'), 'utf8')
  );
  const version = packageJson.version;
  const build = getBuildNumber();

  console.log(`Syncing version ${version} (build ${build}) to all platform configs...`);

  const buildGradlePath = path.join(__dirname, '../app/android/app/build.gradle');
  if (fs.existsSync(buildGradlePath)) {
    fs.writeFileSync(buildGradlePath, applyGradleVersion(fs.readFileSync(buildGradlePath, 'utf8'), version));
    console.log(`✓ Updated ${buildGradlePath} (versionName=${version}; Gradle computes versionCode)`);
  }

  const xcodeProjectPath = path.join(__dirname, '../app/ios/App/App.xcodeproj/project.pbxproj');
  if (fs.existsSync(xcodeProjectPath)) {
    fs.writeFileSync(xcodeProjectPath, applyXcodeVersion(fs.readFileSync(xcodeProjectPath, 'utf8'), version));
    const buildNumberPath = path.join(__dirname, '../app/ios/App/BuildNumber.xcconfig');
    fs.writeFileSync(buildNumberPath, buildNumberXcconfig(build));
    console.log(`✓ Updated ${xcodeProjectPath} (MARKETING_VERSION=${version}) and ${buildNumberPath} (CURRENT_PROJECT_VERSION=${build})`);
  }

  // In GitHub Actions, expose the build number to later steps so the
  // electron-builder ${env.BUILD_NUMBER} macro and rename steps can use it.
  if (process.env.GITHUB_ENV) {
    fs.appendFileSync(process.env.GITHUB_ENV, `BUILD_NUMBER=${build}\n`);
    console.log(`✓ Exported BUILD_NUMBER=${build} to GITHUB_ENV`);
  }

  console.log(`✅ Synced version ${version}, build ${build}`);
}

if (require.main === module) {
  main();
}

module.exports = { getBuildNumber, applyGradleVersion, applyXcodeVersion, buildNumberXcconfig };
